### PR TITLE
Updated 404

### PR DESCRIPTION
**Pull request by GautierLePire**
Just a grammar fix. Kept it as absurd as it was.

### CODE REVIEW

**Comment by cabellwg** [comment]
Merci beaucoup! It's supposed to be a reference to _La Trahison des Images_ by Rene Magritte, and that's why I used "trahison". Will "l'imposture" preserve that reference?

**Comment by GautierLePire** [comment]
Oh, didn't get the reference, I thought that painting was called "Ceci n'est pas une pipe".
The title should be negative. I'll rewrite this as such:

> Ceci n'est pas une page 
>
> Desolé, il est impossible de trouver cette page. Mais vous êtes bien en train de lire une page, non ? Le fait que n'import quoi soit une page est la Trahison des internets. Soyez prudent, ne vous perdez pas dans le surréalisme. J'espère que vous pouvez comprendre le français.

It translates to

> This is not a page
>
> Sorry, this page couldn't be found. But you're reading a very page, aren't you? The fact that everything is a page is the Treachery of internets. Be careful, don't get lost in surrealism. I hope you can understand French.

**Comment by cabellwg** [comment]
The title should be positive! It is a page! In the painting, it’s not a pipe, it’s a picture of a pipe, but here we have the opposite, that a page wasn’t found, but this is, in fact, a page!

Sorry for the confusion, I like taking metaphors way further than reasonable.

**Comment by GautierLePire** [comment]
The 404 page is a page, right ? So is the pipe. It's not the opposite.

**Comment by cabellwg** [comment]
The pipe is not a pipe, it’s merely a representation of a pipe:

> The famous pipe. How people reproached me for it! And yet, could you stuff my pipe? No, it's just a representation, is it not? So if I had written on my picture 'This is a pipe', I'd have been lying!
> René Magritte

His pipe is just a picture, but my “not a page” is actually a page.

**Comment by GautierLePire** [comment]
Ok, thank you for that brain-ache
Then, make the title "Ceci est une page", but the reference is well hidden.
Or even more absurd "Ceci n'est pas une pipe", because that's actually the truth
Whatever you settle with, ping me, I'll have a good laugh

**Comment by cabellwg** [comment]
Refactor is live, thanks so much for your help! My only experience with French is the 4 years I took in high school, so I think you have better qualifications than I do. I love that you opened a PR for this, that's really awesome! I always like to correct people's English grammar, so my grammar better be right (even in French 😂). And I think we both did what it explicitly said not to do, which is to get lost in the surrealism of it all!

**Comment by GautierLePire** [comment]
That was clearly the craziest pull request I took part in!
And this all started because I saw your vim-exit plugin somewhere on the web. (I had to google "how to exit vim" more than once.)

Have a nice day!

**Pull request merged**
